"""Alter vacancies

Revision ID: 08e99a1d3981
Revises: bcb17a320366
Create Date: 2025-12-18 11:06:57.281694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e99a1d3981'
down_revision: Union[str, None] = 'bcb17a320366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('external_company_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'external_company_id')
    # ### end Alembic commands ###
