"""Allow description be nullable

Revision ID: 4bcaaaa8bc57
Revises: e5b3bcdc4a78
Create Date: 2025-12-18 11:25:56.846013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bcaaaa8bc57'
down_revision: Union[str, None] = 'e5b3bcdc4a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('vacancies', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('companies', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
