"""Add cascade deletion

Revision ID: 928b576ca533
Revises: 4bcaaaa8bc57
Create Date: 2025-12-19 02:28:04.320286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928b576ca533'
down_revision: Union[str, None] = '4bcaaaa8bc57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vacancies_company_id_fkey', 'vacancies', type_='foreignkey')
    op.create_foreign_key(None, 'vacancies', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.create_foreign_key('vacancies_company_id_fkey', 'vacancies', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
